- name: Playbook with Variables
  hosts: local
  connection: local
  become: true
  vars:
    course_name: "Ansible for Beginners"
    Duration: "4 weeks"
    trainer: "John Doe"

  tasks:
    - name: Print the variable
      vars:
        course_name: "Ansible for Baby"
        Duration: "5 weeks"
        trainer: "John Snow"
      ansible.builtin.debug:
        msg: "Hello Course Name: {{ course_name }}, Duration: {{ Duration }}, Trainer: {{ trainer }}. Thanks for joining the course!"

  tasks:
    - name: Print the variable
      ansible.builtin.debug:
        msg: "Hello Course Name: {{ course_name }}, Duration: {{ Duration }}, Trainer: {{ trainer }}. Thanks for joining the course!"