- name: Playbook with Variables
  hosts: local
  connection: local
  vars_files:
    - course.yml

  tasks:
    - name: Print the variable
      ansible.builtin.debug:
        msg: |
          Hello Course Name: {{ course_name }}
          Duration: {{ Duration }}
          Trainer: {{ trainer }}
          Description: {{ course_description }}
          Outline: {{ course_outline }}
          Prerequisites: {{ course_prerequisites }}

        