- name: prompt for user input
  hosts: local
  connection: local
  tasks:
    - name: Prompt for user input
      ansible.builtin.prompt:
        name: "user_name"
        prompt: "Please enter your name"
        private: no
  tasks:      
    - name: Print the user input
      ansible.builtin.debug:
        msg: "Hello {{ user_name }}, welcome to the Ansible course!"